# Generated by Django 5.2.3 on 2025-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('meta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
