# Generated by Django 5.2.3 on 2025-07-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
